blog/urls.py
# coding=utf-8
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import  views
from  django.conf  import settings


urlpatterns = [
   url(r'^index/$',views.index),
   url(r'^article/(?P<article_id>[0-9]+)$',views.article_page,name='article_page'),
   url(r'^editor/(?P<article_id>[0-9]+)$',views.editor_page,name='editor_page'),

   url(r'^edit_article/$', views.add_article,name="add_article"),

   url(r'^edit_article/action$', views.edit_action,name='edit_action'),

   url(r'^login/$', views.login,name="login"),

   url(r'^login/logins/$', views.logins,name="logins"),

   url(r'^register/$', views.register,name="register"),

   url(r'^register_user_info$', views.register_user_info,name="register_user_info"),

   url(r'^add_article/(?P<article_id>[0-9]+)$', views.editor_page,name="add_article"),

   url(r'^login_ajax/$', views.login_ajax,name="login_ajax"),
   url(r'^user_main/$', views.user_main,name="user_main"),
   url(r'^ajax_register_info/$', views.ajax_register_info,name="ajax_register_info"),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=16, default='title')
    content = models.TextField(null=True)
    def __unicode__(self):
        return self.title
class User(models.Model):
    username = models.IntegerField(max_length= 11,primary_key=True)
    password =models.CharField(max_length=16)

blog/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import  HttpResponse
from . import models
import logging
import  json
from django.contrib.auth import authenticate

logger = logging.getLogger('stu')

#使用表单登录
def logins(request):
    username =request.POST.get('username','USERNAME')
    password = request.POST.get('password', 'PASSWORD')
    print ('asas')
    try:
        user= models.User.objects.get(username=username)
        if password == user.password:
            return render(request, 'user_main.html')
        else:
            return render(request, 'add_article.html')
    except:
        return render(request, 'add_article.html')

#使用ajax登录
def login_ajax(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        try:
            user = models.User.objects.get(username=username)
            if password == user.password:
                return HttpResponse(1)
            else:
                return HttpResponse(2)
        except:
            return HttpResponse(3)


#进入用户注册界面
def register(request):
    return  render(request,'register.html')

#进入用户注册界面
def register(request):
    return  render(request,'register.html')

#使用表单注册用户信息
def register_user_info(request):
    username = request.POST.get('username','USERNAME')
    password = request.POST.get('password', 'PASSWORD')
    user=models.User.objects.create(username=username,password=password)
    return  render(request,'register.html')

#使用ajax注册用户信息
def  ajax_register_info(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = models.User.objects.filter(username=username).first()
    if(user==None):
        user = models.User.objects.create(username=username, password=password)
        #需要判断
        return HttpResponse(1)

    else:
        return HttpResponse(2)







def index(request):
    articles=models.Article.objects.all()
    return render(request,'index.html',{'articles':articles})


def article_page(request,article_id):
    article =models.Article.objects.get(pk=article_id)
    return  render(request,'article_page.html',{'article':article})

def editor_page(request,article_id):
    if int(article_id)==0:
        return render(request, 'editor_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request,'editor_page.html',{'article':article})

def add_article(request):
    return render(request,'add_article.html')

def edit_action(request):
     title =request.POST.get('title','TITLE')
     content = request.POST.get('content','CONTENT')
     article_id =request.POST.get('article_id','0')
     if int(article_id)==0:
         models.Article.objects.create(title=title,content=content)
         articles = models.Article.objects.all()
         return render(request, 'index.html', {'articles': articles})
     else:
         article = models.Article.objects.get(pk=int(article_id))
         article.title=title
         article.content=content
         article.save()
         articles = models.Article.objects.all()
         return render(request, 'index.html', {'articles': articles})
         return render(request, 'index.html', {'articles': articles})


def login(request):
    return render(request,'login.html')


def user_main(request):
    return  render(request,'user_main.html')





def register_user_info(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user=models.User.objects.create(username=username,password=password)
    return  render(request,'register.html')

def loginss(request):
    username =request.POST.get('username','USERNAME')
    password = request.POST.get('password', 'PASSWORD')
    return HttpResponse(1)

myblog/views.py
from django.http  import HttpResponse

def hello(request):
    return HttpResponse('helloword')

blog/templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <label>文章标题：
    <input type="text" name="title" >
    </label>
    <label>文章内容：
    <input type="text" name="content" >
    </label>
    <input type="submit">
</form>
</body>
</html>

blog/templates/add_article_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <label>文章标题：
    <input type="text" name="title" >
    </label>
    <label>文章内容：
    <input type="text" name="content" >
    </label>
    <input type="submit">
</form>
</body>
</html>

blog/templates/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<h3>{{ article.content }}</h3>
<a href>sad</a>
</body>
</html>

blog/templates/editor_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

        <input  type="hidden" name="article_id" value="{{ article.id | default:'0'}}" >
        <label>文章标题：
        <input type="text" name="title" value="{{ article.title }}">
        </label>
        <label>文章内容：
        <input type="text" name="content" value="{{ article.content }}">
        </label>
        <input type="submit" value="修改">


</form>

</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<a  href=""></a>
{% for article  in articles%}
    <a href="{% url 'blog:article_page' article.id %}"><h1>{{ article.title }}</h1></a>
    <a href="{% url 'blog:add_article' article.id %}">编辑</a>
{% endfor %}
<a href="{% url 'blog:add_article' 0 %}"><h1>添加文章</h1></a>
</body>
</html>

blog/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录界面</title>
</head>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"> </script>
<script>
    $(function(){

        //点击注册按钮
        $('#register').click(function () {

            window.location.href = '/blog/register/';
        });

        //使用ajax登录
        $('#login').click(function() {
            username = $('#username').val();
            password = $('#password').val();
            $('#username_info').text("")
            $('#password_info').text("")
            $.ajax({
                url:"/blog/login_ajax/",
                type:'post',
                data:{csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),'username':username,'password':password},
                success:function(data){
                    if(data==1)
                        window.location.href = '/blog/user_main/';
                    else  if(data==2)
                        $('#password_info').text("密码错误")
                    else if(data==3)
                        $('#username_info').text("用户不存在")
                },
                error:function () {
                  alert("出错啦...")
                },
            });
        });

    });


</script>
<body>
<form  method="post" action="{% url 'blog:logins' %}">
       {% csrf_token %}
        <table>
            <tr>
                <td>  <label>手机号：</label></td>
                <td>  <input type="text"    name="username" id="username"></td>
                <td>  <span  id="username_info"></span></td>
            </tr>

            <tr>
                <td> <label>密码：</label></td>
                <td> <input type="password"  name="password" id="password"></td>
                <td> <span  id="password_info"></span> </td>
            </tr>
        </table>

       <input type="submit" value="提交表单登录">
</form>

<input type="button" id="login" value="使用ajax登录" >
<input type="button" id="register" value="注册" >

</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
    <script  type="text/javascript"  src="{%static  "js/jquery.js" %}"></script>
</head>
<script>

    $(function () {
        $('#register').click(function () {
            username = $('#username').val();
            password = $('#password').val();
            re_password = $('#re_password').val();
            if (password == ''){
                alert('密码不能为空')
                return false
            }
            if (re_password == ''){
                alert('请输入确认密码')
                return false
            }
            if (password != re_password) {
                $('#password').val('');
                $('#re_password').val('');
                alert('两次密码不一致,请重新输入')
                return false
             }
              $.ajax({
                url:"/blog/ajax_register_info/",
                type:'post',
                data:{csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),'username':username,'password':password},
                success:function(data){
                    if(data==1){
                        alert('注册成功')
                        window.location.href = '/blog/login/'
                    }
                    else if(data==2){
                          // $('#username_info').text("手机号已被注册")第一次注册失败之后，第二次会报错
                        alert("手机号已被注册")
                        window.location.href = '/blog/register/';
                    }

                },
                error:function () {
                  alert("出错啦...")
                },
            });


        });


    });
</script>
<body>
<form  method="post"  action="{% url 'blog:register_user_info' %}" >
    {% csrf_token %}
    <table>
        <tr>
            <td> <label>请输入手机号：</label>  </td>
            <td> <input type="text"  id="username"   name="username"></td>
            <td> <span  id="username_info"></span></td>
        </tr>

         <tr>
            <td> <label>请输入密码：</label> </td>
            <td> <input type="password" id="password"  name="password"></td>
             <td></td>
            <td><span  id="password_info"></span></td>
        </tr>

        <tr>
            <td> <label>请再次输入密码：</label> </td>
            <td> <input type="password" id="re_password"  name="re_password"></td>
             <td></td>
            <td><span  id="re_password_info"></span></td>
        </tr>

    </table>

    <input type="submit"  value="提交表单注册">

</form>
    <input type="button"  id="register" value="使用ajax注册">

</body>
</html>

blog/templates/user_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主界面</title>
</head>
<body>
登陆成功
</body>
</html>